- .env
- cmd/init/db.go
- cmd/main/main.go
- cmd/main/misc.go
- config/config.yaml
- config/models/user.json
- go.mod
- go.sum
- integration-test/const.js
- integration-test/rest-user.js
- pkg/handler/convertor.go
- pkg/handler/handler.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- refactor error message https://github.com/instill-ai/vdp/issues/112
This commit
- refactor error messages
- make email field required
- update mgmt-backend port from 8080 to 8084
> fix: refactor error code

- .env
- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/images.yml
- .github/workflows/releases.yml
- .pre-commit-config.yaml
- config/config.yaml
- go.mod
- go.sum
- integration-test/rest-user.js
- pkg/handler/handler.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- CORS configuration is set in docker-compose files
- replace custom endpoint style `:` with `/`
This commit
- upgrade pre-commit hooks
- update action scripts
- refine .env file
- remove cors default config
- adopt latest protogen-go
> chore: change config and usage metric

- Makefile
- integration-test/const.js
- integration-test/grpc-private-user.js
- integration-test/grpc-public-user.js
- integration-test/grpc.js
- integration-test/proto/vdp/healthcheck/v1alpha/healthcheck.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/api/annotations.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/api/client.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/api/field_behavior.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/api/http.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/api/resource.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/longrunning/operations.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/rpc/status.proto
- integration-test/proto/vdp/mgmt/v1alpha/google/type/date.proto
- integration-test/proto/vdp/mgmt/v1alpha/healthcheck.proto
- integration-test/proto/vdp/mgmt/v1alpha/mgmt.proto
- integration-test/proto/vdp/mgmt/v1alpha/mgmt_private_service.proto
- integration-test/proto/vdp/mgmt/v1alpha/mgmt_public_service.proto
- integration-test/proto/vdp/mgmt/v1alpha/protoc-gen-openapiv2/options/annotations.proto
- integration-test/proto/vdp/mgmt/v1alpha/protoc-gen-openapiv2/options/openapiv2.proto
Because
- test gRPC methods
This commit
- add gRPC test cases
> chore: add grpc test cases

- cmd/init/main.go
- integration-test/const.js
- integration-test/grpc-private-user.js
- integration-test/rest-private-user.js
- pkg/constant/constant.go
- pkg/handler/privatehandler.go
- pkg/handler/publichandler.go
- pkg/middleware/interceptor.go
Because
- we want to refactor the default user info
This commit
- update the default user info
> refactor: change default user information

- cmd/init/main.go
- cmd/main/main.go
- pkg/external/external.go
- pkg/handler/privatehandler.go
- pkg/handler/publichandler.go
- pkg/logger/logger.go
- pkg/middleware/misc.go
- pkg/repository/repository.go
- pkg/usage/usage.go
Because
- the edition is not initialised in usage
This commit
- initialise edition in usage
> chore: fix usage edition initialisation

- .github/workflows/integration-test.yml
- Makefile
- README.md
- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/external/external.go
- pkg/handler/publichandler.go
Because
- retire `DISABLEUSAGE` and change to `USAGE_ENABLED` in VDP
- retire `ITMODE` and change to `ITMODE_ENABLED` in VDP
This commit
- update `disableUsage` naming
- update `ITMODE` naming
Fixes INS-867
> chore: update usage naming

- go.mod
- go.sum
- pkg/handler/publichandler.go
- pkg/repository/influx.go
Because
- update metric field name to align with backend
This commit
- update metric field name to align with backend
> chore(metric): update metric field name

- config/config.yaml
Because
- update bucket name
This commit
- update bucket name
> chore: update bucket name

- config/config.go
- config/config.yaml
- pkg/external/external.go
- pkg/service/metric.go
Because
- use url to support influxdb cloud
This commit
- use url to support influxdb cloud
> chore: use url to support influxdb cloud

- cmd/main/main.go
- pkg/external/external.go
Because
- update influx config for mgmt-backend-cloud
This commit
- update influx config for mgmt-backend-cloud
> chore: update influx config for mgmt-backend-cloud

- integration-test/grpc-public-user.js
- integration-test/grpc.js
- integration-test/proto/base/mgmt/v1alpha/metric.proto
- integration-test/proto/base/mgmt/v1alpha/mgmt_public_service.proto
- integration-test/rest-public-user.js
- integration-test/rest.js
Because
- add test for metric api
This commit
- add test for metric api
> test(metric): add test for metric api

- integration-test/grpc-public-user.js
- integration-test/rest-public-user.js
Because
- fail test if influxdb has data from previous backend test
This commit
- account for possible datapoint present in influxdb
> test(metric): account for possible datapoint present in influxdb

- go.mod
- go.sum
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- support table view with pagination for pipeline/connector dashboard
This commit
- add list table records endpoints for pipeline and connector
> chore(metric): add table view metric endpoint

- integration-test/grpc-public-user.js
- integration-test/proto/base/mgmt/v1alpha/metric.proto
- integration-test/proto/base/mgmt/v1alpha/mgmt_public_service.proto
- integration-test/rest-public-user.js
Because
- add tests for metric table endpoints
This commit
- add tests for metric table endpoints
> test(metric): add tests for metric table endpoints

- integration-test/rest-public-user.js
Because
- the metric test has bug
This commit
- fix metric test bug
> chore: fix metric test bug

- cmd/main/main.go
- pkg/external/external.go
Because
- fix missing config for dynamic target host assignment
This commit
- add missing external config
> chore: fix missing external config

- pkg/repository/influx.go
Because
- have duplicate entries for the same pipeline after rename for `/tables` endpoint
This commit
- update `/tables` endpoint to support latest resource id mapping
> chore(metric): update /tables to support id mapping

- .github/workflows/integration-test.yml
- Makefile
- integration-test/const.js
Because
- we consolidated three gateways into one.
This commit
- update integration test to support consolidated gateway
> chore: update integration test to support consolidated gateway

- pkg/handler/privatehandler.go
- pkg/handler/publichandler.go
Because
- the error code of token creation was wrong
This commit
- fix error code of token creation
- remove unused code
> chore(handler): fix error code of token creation

- go.mod
- go.sum
- pkg/handler/privatehandler.go
- pkg/handler/publichandler.go
- pkg/service/service.go
Because
- we need API endpoints for organization managament
This commit
- add organization update/delete and admin endpoints
> chore(handler): add organization update/delete and admin endpoints

- go.mod
- go.sum
- pkg/service/service.go
Because
- we need to know the number of pipelines of the user or organization
This commit
- add ListUserPipelines and ListOrganizationPipelines functions
> chore(service): add ListUserPipelines and ListOrganizationPipelines functions

- pkg/handler/publichandler.go
- pkg/service/service.go
Because
- we can't successfully patch user profile_data
This commit
- fix profile_data patch bug
> chore(handler): fix profile_data patch bug

- pkg/acl/acl.go
- pkg/service/service.go
Because
- user should not see other users' pending invitations
This commit
- fix wrong role, the role should not contain `pending` prefix
- pending invitations can only be seen by owner and the user himself
> chore(acl): user should not see other users' pending invitations

- cmd/main/main.go
- pkg/constant/constant.go
- pkg/service/convertor.go
Because
- we need to limit the avatar image size
This commit
- increase grpc max message size
- limit avatar image size
> chore(service): increase grpc max message size and limit avatar image size

- pkg/acl/model.go
Because
- We want to implement access control for Instill Model.
This commit
- Add FGA model for Model
> feat: add FGA model for Model

- pkg/service/service.go
Because
- The membership endpoint will be broken after organization deleted.
This commit
- Fixes the bug.
> fix: fix the membership endpoint broken after organization deleted

- .github/workflows/integration-test.yml
- cmd/init/main.go
- go.mod
- go.sum
- pkg/acl/acl.go
- pkg/acl/model.go
- pkg/service/convertor.go
Because
- We want to provide a new `admin` role for organization members, which allows them to edit the organization and invite other members
This commit
- Adds `admin` role for organizations.
> feat: add `admin` role for organization

- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/external/external.go
- pkg/repository/influx.go
Because
- We're using 2 separate packages to initialize an InfluxDB repository.
This commit
- Make configuration part of the InfluxDB repo initialization.
> chore: refactor InfluxDB repository for better injection

- .gitignore
- pkg/acl/model.go
Because
we need to use openfga for knowledge base access control
This commit
add auth model of knowledge base
> feat(mgmt): add knowledge base acl model

- cmd/init/main.go
- cmd/init/preset/presetcreator.go
- go.mod
- pkg/repository/influx.go
Because
- The preset creator will be used in another package.
This commit
- Exposes the preset creator.
> refactor: expose preset creator

- integration-test/rest-public-user.js
Because
- wrong variable.
This commit
- fix the wrong variable "totalSize" and "nextPageToken"
> fix(test): fix wrong property in testing

- pkg/constant/constant.go
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/repository/influx_transpiler.go
- pkg/repository/repository.go
- pkg/repository/transpiler.go
This commit
- supports filter users by email
> feat(service): support filter users by email
