- .env
- cmd/main/main.go
- configs/config.yaml
- configs/configs.go
- docker-compose.yml
Because
- support CORS to integrate with console UI
This commit
- update CORSOrigins to be string separated by ","
- support CORS ([Reference](https://github.com/grpc-ecosystem/grpc-gateway/blob/24434e22fb9734f1a62c81c4ea246125d7844645/examples/internal/gateway/handlers.go#L32))
- update project name to `instill-vdp`
> fix: support CORS

- cmd/main/main.go
- pkg/handler/handler.go
- pkg/usage/usage.go
Because
- usage service could be not available and the mgmt server should be resilient with this situation.
This commit
- check the connection to the usage service then report only have a connection
> chore: resilient with non-working usage service

- integration-test/grpc-public-user.js
Because
- we want to separate the restore to default user test to the other tests
This commit
- update the test message
> test: update test message

- go.mod
- go.sum
- pkg/handler/privatehandler.go
Because
- ValidateToken() is not useful since we only have access_token from pipeline-backend
This commit
- remove ValidateToken() endpoint
> chore: remove ValidateToken() endpoint

- .github/workflows/integration-test.yml
- Makefile
- integration-test/const.js
- integration-test/grpc.js
- integration-test/rest.js
Because
- Need to simplify the integration test mode
This commit
- Add `API_GATEWAY_HOST`, `API_GATEWAY_PORT` and `API_GATEWAY_PROTOCOL` var. to simplify the integration test setting
> chore: refactor integration test mode

- .github/CODEOWNERS
- cmd/main/main.go
- go.sum
- pkg/external/external.go
- pkg/usage/usage.go
Because
- we want to limit the use of global variables, as it will affect reusing the packages
This commit
- update usage functions
- update code owner to @donch1989
> refactor: update usage functions to not use global variables

- cmd/init/main.go
- cmd/main/main.go
- pkg/external/external.go
- pkg/handler/privatehandler.go
- pkg/handler/publichandler.go
- pkg/logger/logger.go
- pkg/middleware/misc.go
- pkg/repository/repository.go
- pkg/usage/usage.go
Because
- the global variable is used in package functions. When importing the package, the global variable is not initialised, causing trouble
- logger requires debug level
This commit
- limit the use of global variables only in main packages
- update logger
> chore: limit the use of global variable and update logger

- go.mod
Because
- v0.3.2 is published accidentally, see https://pkg.go.dev/github.com/instill-ai/mgmt-backend/pkg/repository?tab=versions
This commit
- retract v0.3.2
> chore: retract accidentally published version v0.3.2

- LICENSE
- config/models/user.json
Because
- our mission is to make AI accessible to everyone. The best way to achieve this is to make VDP free to use and source available to everyone, while ensuring we safely create a sustainable business. Therefore, we chose ELv2 since it is very permissive. On one hand, this allows us to provide users with free access to our source code, the permission to modify it. On the other hand, we've released Instill Cloud, a fully-managed public cloud service built upon VDP that offers additional features. With the license, we don't have to worry about our project being taken by some other companies for monetization.
This commit
- update LICENSE
> chore(license): update VDP license to ELv2 and MIT

- integration-test/const.js
- integration-test/grpc-private-user.js
- integration-test/grpc-public-user-with-jwt.js
- integration-test/grpc-public-user.js
- integration-test/grpc.js
- integration-test/proto/vdp/mgmt/v1alpha/mgmt.proto
- integration-test/proto/vdp/mgmt/v1alpha/mgmt_private_service.proto
- integration-test/rest-private-user.js
- integration-test/rest-public-user-with-jwt.js
- integration-test/rest-public-user.js
- integration-test/rest.js
Because
- the integration tests are not up-to-date and can't be passed in microservice mode
This commit
- update the proto files
- remove tests for non-exist endpoints
- replace `headers` with `metadata` for gRPC tests to fix the k6 warning
> test: fix tests in direct microservice mode

- integration-test/rest-public-user.js
Because
- add missing filter to avoid querying the leftover datapoint from previous tests
This commit
- add missing filter to avoid querying the leftover datapoint from previous tests
> test(metric): add missing filter

- cmd/init/main.go
- config/config.go
- config/config.yaml
Because
- have a persistent user uuid for the default user
This commit
- add `defaultuseruuid` as config for env variable pass in
> chore(config): add support for persistent default user uuid

- cmd/main/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- integration-test/grpc-public-user.js
- integration-test/rest-public-user.js
- pkg/constant/constant.go
- pkg/external/external.go
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/repository/transpiler.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- support pipeline release data format for metric data
- allow resource id querying in metric endpoints
This commit
- support pipeline release data format for metric data
- support resource uid lookup
Resolves INS-1734
Resolves INS-1729
> chore(metric): adopt pipeline release data format and support uid lookup

- pkg/middleware/misc.go
- pkg/repository/influx.go
- pkg/service/metric.go
Because
- support jwt-sub verification for api calls
- support always return current pipeline name for metric charts
This commit
- add header injection for jwt-sub
- update /charts endpoints
Resolves INS-1773
> chore(metric): add jwt injection and update chart queries

- pkg/repository/influx.go
Because
- misbehave pagination due to group keys
This commit
- fix /tables pagination
> chore(metric): fix /tables pagination

- pkg/repository/influx.go
Because
- mismatch group keys impact `join` action performance
This commit
- fix /tables pre-join action group key mismatch
> chore(metric): fix /tables pre-join action group key mismatch

- pkg/repository/influx.go
Because
- mismatch variable type when extracting values from metric datapoint
This commit
- fix mistype record value
> chore(metric): fix mistype record value

- pkg/repository/transpiler.go
- pkg/service/metric.go
Because
- fallback to `id` query will have the same issue as before, records mix different pipelines together
This commit
- remove logic to fallback to `id` query if `uid` lookup missed
> chore(metric): remove id query fallback

- cmd/main/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- integration-test/const.js
- integration-test/grpc-private-user.js
- integration-test/grpc-public-user.js
- integration-test/rest-public-user.js
- pkg/constant/constant.go
- pkg/datamodel/convertor.go
- pkg/datamodel/datamodel.go
- pkg/datamodel/tokengenerator.go
- pkg/db/migration/000002_init.up.sql
- pkg/handler/publichandler.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- we need to support `api_token`, so that the developer can build a application using `api_token` to connect Instill-Core
This commit
- support `api_token` authentication
- add tokens management endpoints
> feat(auth): support `api_token` authentication

- cmd/init/main.go
- pkg/db/migration/000002_init.up.sql
Because
- the default user creation might be duplicated.
This commit
- fix default user creation bug
> fix(init): fix default user creation bug

- Dockerfile
Because
- go `1.21` complains `/lib/aarch64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found` when `CGO_ENABLED=1`
This commit
- set `CGO_ENABLED=0`
> chore(Dockerfile): build go binary without cgo

- cmd/main/main.go
- go.mod
- go.sum
- pkg/external/external.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- the protogen-go pkg is outdated
This commit
- adopt latest protogen-go package
> chore(deps): adopt latest protogen-go

- pkg/middleware/interceptor.go
Because
- we should not wrap internal error
This commit
- do not wrap internal error
> chore(middleware): do not wrap internal error

- pkg/handler/publichandler.go
Because
- the ExistUsername() didn't return not `Exists: false`
This commit
- fix ExistUsername bug
> chore(handler): fix ExistUsername bug

- go.mod
- go.sum
- integration-test/grpc-public-user.js
- integration-test/proto/core/mgmt/v1alpha/metric.proto
- integration-test/proto/core/mgmt/v1alpha/mgmt.proto
- integration-test/proto/core/mgmt/v1alpha/mgmt_private_service.proto
- integration-test/proto/core/mgmt/v1alpha/mgmt_public_service.proto
- pkg/handler/publichandler.go
Because
- we need an API to determine the availability of a namespace id and its type
This commit
- remove ExistUsername API  and add new CheckNamespace API
> refactor(core): retire ExistUsername API and add CheckNamespace API

- go.mod
- go.sum
- pkg/handler/publichandler.go
Because
- we simplified the message of CheckNamespace endpoint
This commit
- adopt latest Core protobufs
> chore(deps): adopt latest Core protobufs

- pkg/handler/publichandler.go
Because
- organization should be abled to revoke user membership
This commit
- fix organization can not revoke user membership
> fix(handler): fix organization can not revoke user membership

- go.mod
- go.sum
- pkg/service/convertor.go
Because
- we need to embed owner information in the organization payload
This commit
- add owner field in organization payload
> chore(service): add owner field in organization payload

- pkg/handler/publichandler.go
Because
- there are some typos
This commit
- fix typos in public hander
> chore(handler): fix typos

- integration-test/const.js
- integration-test/grpc-public-user-with-jwt.js
- integration-test/grpc.js
- integration-test/rest-public-user-with-jwt.js
- integration-test/rest.js
- pkg/constant/constant.go
- pkg/handler/publichandler.go
- pkg/middleware/misc.go
- pkg/service/cache.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- User and organization data fall into the category of data that is more frequently read than written. Implementing a cache mechanism can enhance performance.
This commit
- Implement cache mechanism for user and organization data with write-through and lazy-loading approach
> feat: implement cache mechanism

- pkg/repository/repository.go
- pkg/service/cache.go
- pkg/service/service.go
Because
- the original `api_token` cache mechanism is not robust, the cache might be missed and not being updated.
This commit
- fix `api_token` cache miss bug
> fix: fix `api_token` cache miss bug

- cmd/main/main.go
- pkg/usage/usage.go
Because
- we don't want to use constant directly in `usage` struct
This commit
- pass `defaultUserID` into `usage` struct
> refactor: pass `defaultUserID` into `usage` struct

- go.mod
- go.sum
- pkg/usage/usage.go
Because
- we are missing org session data
This commit
- add `org_usages` in `MgmtUsageData`
> refactor(usage): add org data in usage report

- pkg/service/metric.go
- pkg/service/service.go
Because
- When deleting an organization, it is required to automatically remove all associated resources.
This commit
- Deletes related resources when an organization is deleted.
> feat: delete related resources when an organization is deleted

- cmd/worker/main.go
- config/config.go
- config/config.yaml
- go.mod
Because
- make temporal namespace programmatically created to remove the `temporal-admin-tools` container at launch
This commit
- add initialisation temporal namespace logic in the worker `main.go`
- the implementation will skip the namespace creation if it already exists
> chore(worker): create temporal namespace at launch

- Dockerfile
Because
- we want fine-grained control for dependency status with healthcheck at docker compose up
This commit
- add `sh` and `wget` for distroless image
> ci(Dockerfile): add sh and wget

- go.mod
- go.sum
Because
- fix dependabot alerts:
- https://github.com/instill-ai/mgmt-backend/security/dependabot/22
- https://github.com/instill-ai/mgmt-backend/security/dependabot/21
This commit
- update `go.mod` and `go.sum`
> chore(dep): fix dependabot alerts

- go.mod
- go.sum
- pkg/service/convertor.go
- pkg/service/service.go
- pkg/usage/usage.go
Because
- `usage-server` is using `AuthenticatedUser` in `usage` report
This commit
- adopt latest protogen-go
- use `AuthenticatedUser` in `usage` report
> fix(usage): send usage report with `AuthenticatedUser`

- pkg/service/service.go
Because
- We should allow organization deletion even if no pipeline-backend has started.
This commit
- Allows deletion of an organization when no pipeline-backend has started.
> chore: allow delete organization when no pipeline-backend started

- pkg/service/cache.go
Because
- When we deploy Instill-Core in a multi-region cluster, we need to consider the cache invalidation problem. In our use cases, we can add TTL to all cached data to help invalidate outdated cache.
This commit
- Sets TTL for owner cache.
> feat: set TTL to owner cache

- cmd/init/main.go
- cmd/main/main.go
- config/config.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- Since there will be replication lag in the database replica, we will encounter the "read-after-write inconsistency" problem when deploying Core in a multi-region cluster. In our use case, we can choose the "Pinning User to Primary Database" approach as our first step. This means that after the user mutates some data, there will be a small time frame during which this user will always read data from the primary database, regardless of their location. This way, we can ensure read-after-write consistency.
This commit
- Pins the user to read from the primary database for a certain time frame after mutating the data.
> feat: pin the user to read from the primary database for a certain time frame after mutating the data

- cmd/main/main.go
- config/config.go
- pkg/acl/acl.go
- pkg/handler/publichandler.go
- pkg/service/convertor.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- In the multi-region deployment, we will separate the read/write operations into different databases and OpenFGA engines.
This commit
- Adds connection settings for OpenFGA read replica.
- Separates read/write modes into different OpenFGA engines.
> feat: support OpenFGA read replica

- cmd/init/main.go
- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/middleware/middleware.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/convertor.go
- pkg/service/service.go
Because
- Putting the avatar as base64 in the user, organization and pipeline response is not a good choice. We should provide a link for the Console to fetch the avatar asynchronously.
This commit
- Implements endpoints for user and organization avatars.
> feat: implement endpoints for user and organization avatars

- pkg/datamodel/datamodel.go
- pkg/db/migration/000006_init.up.sql
- pkg/repository/repository.go
- pkg/repository/repository_test.go
Because
- Credit table references the owner by ID but it is a field that might become modifiable.
- We want to trace the credit history of an owner.
- We need to avoid concurrent credit subtractions to corrupt data (subtraction starts by checking the remaining credit).
This commit
- Updates the table to reference the `user_uid`
- Updates the indices and subtraction method to only add entries, not update them. The credit table becomes a ledger with positive and negative entries.
- Since we have entries that expire, we'll need to cancel them separately to compute the credit successfully.
- A lock mechanism is added to avoid concurrent subtractions to conflict between them.
- This [ledger test](https://github.com/instill-ai/mgmt-backend/pull/198/files#diff-650c1756664dfa9c6d895fbb31ad66a26d0b …
> feat: update credit datamodel

- integration-test/const.js
Because
- We've added new HTTP endpoints without the `/core` prefix.
This commit
- Removes the `/core` HTTP endpoint prefix in HTTP integration test.
> test: remove /core HTTP endpoint prefix in integration test

- pkg/repository/repository.go
Because
- Cloud has custom database methods that also need user pinning.
This commit
- Exports the `CheckPinnedUser` and `PinUser` methods to avoid code duplication.
> chore: export database user pinning logic

- go.mod
- go.sum
- pkg/handler/publichandler.go
- pkg/repository/errors.go
- pkg/repository/repository.go
- pkg/repository/repository_mocksql_test.go
- pkg/service/convertor.go
- pkg/service/service.go
Because
- we want users to be able to target the tokens that can be deprecated.
This commit
- Update token data when the token is used.
> feat: update last use time when api token is used

- cmd/main/main.go
- pkg/repository/influx.go
Because
- Cloud version will call InfluxDB constructor but CE's config won't be initialized.
This commit
- Receives config in constructor.
> fix: receive config in InfluxDB constructor

- cmd/main/main.go
- integration-test/const.js
- integration-test/grpc-private-user.js
- integration-test/grpc-public-user.js
- integration-test/grpc.js
- integration-test/rest-public-user.js
- integration-test/rest.js
Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- Uses camelCase for HTTP bodies.
> feat: use camelCase for HTTP body

- pkg/service/convertor.go
Because
- Currently, if the `last_use_time` is zero, the API returns a zero date, which is confusing.
This commit
- Makes `last_use_time` in `ApiToken` return null for zero value.
> chore(mgmt): make ApiToken last_use_time return null for zero value

- cmd/init/main.go
- go.mod
- go.sum
- pkg/constant/constant.go
- pkg/handler/privatehandler.go
Because
- In Instill Core, we'll provide a "preset" namespace for storing preset resources, such as preset pipelines.
This commit
- Adds script to create the "preset" namespace.
> feat: add script to create `preset` namespace

- go.mod
- go.sum
- pkg/handler/privatehandler.go
Because
- We want to provide an internal helper endpoint to allow other backends to easily query namespace information.
This commit
- Adds a private endpoint `CheckNamespaceByUIDAdmin`
> feat: add private endpoint `CheckNamespaceByUIDAdmin`

- pkg/handler/privatehandler.go
Because
- The `CheckNamespaceByUIDAdmin` should use UID to query.
This commit
- Fixes the bug.
> chore: fix CheckNamespaceByUIDAdmin bug

- go.mod
- go.sum
- pkg/errors/errors.go
- pkg/handler/publichandler.go
- pkg/middleware/interceptor.go
- pkg/repository/influx.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/errors.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- Pipeline and credit endpoints have different params and schemas.
- Some of the information served by the existing endpoints will be handled by the logging feature.
This commit
- Applies contracts defined in https://github.com/instill-ai/protobufs/pull/387
> feat: unify pipeline trigger chart endpoint with credit chart

- go.mod
- go.sum
- integration-test/grpc-public-user.js
- integration-test/proto/core/mgmt/v1beta/metric.proto
- integration-test/proto/core/mgmt/v1beta/mgmt.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_private_service.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_public_service.proto
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- The new dashboard endpoints introduced breaking changes and the clients won't be ready for the upcoming release.
This commit
- Restores the previous dashboard endpoints.
> fix: restore pipeline dashboard enpoints

- pkg/handler/publichandler.go
Because
- Users were unable to invite organization members.
This commit
- Fixes the issue preventing users from inviting organization members.
> fix: fix the issue preventing users from inviting organization members

- pkg/handler/publichandler.go
Because
- The organization can not be updated.
This commit
- Fixes organization can not be updated.
> fix: fix organization can not be updated

- pkg/repository/influx.go
Because
- The `GET https://api.instill.tech/v1beta/metrics/vdp/pipeline/tables` endpoint (for relatively large datasets and time ranges) returned the following error:
```
message: "Invalid query: internal error: panic: arrow/array: index out of range"
```
- The culprit was the `max` function used in the [InfluxDB query](https://github.com/instill-ai/mgmt-backend/blob/main/pkg/repository/influx.go#L186).
This commit
- Replaces the `max` function by `sort` + `first`, which don't produce the error.
> fix(dashboard): broken InfluxDB query on trigger count

- go.mod
- go.sum
- integration-test/grpc-public-user.js
- integration-test/proto/core/mgmt/v1beta/metric.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_public_service.proto
- integration-test/rest-public-user.js
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- Pipeline metrics list endpoint was removed but it has a client.
This commit
- Reintroduces the endpoint contract. It will be removed with the new
dashboard design.
> fix(metric): reintroduce /metrics/vdp/pipeline/triggers endpoint

- .gitignore
- go.mod
- go.sum
- pkg/constant/constant.go
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- dashboard needs API for model trigger count
This commit
- add new metrics API
> feat(metric): model trigger chart record api

- go.mod
- go.sum
- pkg/handler/publichandler.go
- pkg/repository/influx.go
- pkg/service/metric.go
- pkg/service/service.go
Because
- dashboard needs API for model trigger completed/error counts
This commit
- add new metrics API
> feat(metric): model trigger counts api

- go.mod
- go.sum
Because
- using colons in url paths will cause conflicts either in krakend or gin
This commit
- replace colons with `/`
> fix(metric): fix path conflicts

- pkg/service/convertor.go
Because
- we’ve removed the deprecated API endpoint with the `/core` prefix, but it’s still being used in avatar path generation.
This commit
- fixes the avatar path.
> fix(service): fix avatar path

- go.mod
- go.sum
- integration-test/proto/core/mgmt/v1beta/mgmt.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_public_service.proto
Because
- we've updated the enum for user plan.
This commit
- adopts latest `protogen-go` package.
> chore(proto): adopt latest `protogen-go` package

- .github/workflows/coverage.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- Dockerfile
- Makefile
- cmd/main/main.go
- cmd/worker/main.go
- config/config.yaml
- pkg/usage/usage.go
Because
- the current build-time backend versioning logic is wrong.
This commit
- fixed the versioning logic and assigned short commit hash to all backend services.
> ci(workflows): adopt short commit hash for service version

- .github/workflows/integration-test.yml
- go.mod
- go.sum
Because
- usage-client has a a new version to adopt the latest services
This commit
- bumps up the usage-client version
> chore(dep): bump up usage-client version

- cmd/migration/main.go
- config/config.go
- config/config.yaml
- pkg/db/db.go
Because
- The DB version should always be bound to the codebase; we shouldn’t use a config file for it.
This commit
- Removes the DB version from the config file.
> refactor(config): remove db version from config file

- pkg/db/migration/migration.go
This commit
- skips OpenFGA migration if no OpenFGA stores found
> fix(migrate): skips OpenFGA migration if no OpenFGA stores found

- cmd/init/main.go
- cmd/worker/main.go
Because
- the Temporal namespace needs to be created before both `cmd/main` and `cmd/worker`.
This commit
- moves Temporal namespace creation to cmd/init
> fix(cmd): move Temporal namespace creation to cmd/init

- cmd/init/main.go
- config/config.yaml
- go.mod
- go.sum
Because
- The Temporal namespace will now be initialized when the Temporal service starts.
Ref: https://github.com/instill-ai/instill-core/pull/1352
- We now use the shared `instill-core` namespace across all services.
This commit
- Removes Temporal namespace initialization
- Adopts the latest `x/temporal` package to support API key authentication for connecting to Temporal Cloud
> feat(temporal): remove Temporal namespace initialization

- pkg/handler/publichandler.go
- pkg/service/service.go
Because
- Validation was implemented at the handler level but other parts of the
code might call the organization creation service method, and we want
them to have validation as well.
This commit
- Moves the output-only and validation logic to the service method.
> chore(organization): move org creation validation to service

- .github/workflows/integration-test.yml
- pkg/handler/publichandler.go
- pkg/middleware/middleware.go
- pkg/repository/repository.go
Because
- the backend should return `204` instead of `404` when the user avatar hasn't been uploaded yet.
- updating user fields without touching profile.avatar was wiping the avatar due to DB updates writing zero-values.
This commit
- change the response status accordingly.
- Updates `pkg/repository/repository.go` to remove `.Select("*")` in `updateOwner`, letting gorm skip zero-value fields (prevents unintended clearing of `profile.avatar` and similar fields).
> fix(middleware,repository): fix user profile avatar issue
